#!/bin/bash
ids=`relation-ids lb`
unit=$(relation-list -r $ids) 
cat /dev/null > nginx.conf
for i in $unit
do
	ip=$(relation-get -r $ids private-address $i)
	echo $ip >> nginx.conf
done
sed -i 's/.*/server\ &\:8080;/' nginx.conf
cat >> nginx.conf << EOF
    }

    server {
     listen 80;
        location / {
            proxy_pass http://api;
        }
    }
}
EOF
echo -e "events {}\nhttp {\n\tupstream api {\n$(cat nginx.conf)" > nginx.conf

nginx -t -c $JUJU_CHARM_DIR/nginx.conf
if [[ $? == 0 ]]
then
	mv nginx.conf /etc/nginx.conf
	systemctl restart nginx
	open-port 80
fi
